#!/usr/bin/env bash
# PreToolUse guard (Write|Edit|MultiEdit): forbid editing the repo-root CLAUDE.md
# (and the .claude/.agents/.codex skill mirrors). These are GENERATED MIRRORS of
# canonical sources: CLAUDE.md is regenerated from AGENTS.md, and the skill
# mirrors are regenerated from .skills/, both by bin/sync_skills.py. A direct
# edit to a mirror is silently clobbered on the next sync.
#
# USER DIRECTIVE 2026-07-21: add a guard so the agent cannot edit CLAUDE.md
# directly and is instead told to edit AGENTS.md and re-sync. (Prompted by a
# real clobber this session: a CLAUDE.md skill-list edit was overwritten when
# the next sync regenerated it from AGENTS.md.)
#
# On a blocked write, nudge to the canonical source + sync. Exit 2 -> tool call
# blocked, stderr shown to the model.
set -u

payload=$(cat)
path=$(HOOK_PAYLOAD="$payload" python3 - <<'PYEOF'
import os, json
try:
    d = json.loads(os.environ.get("HOOK_PAYLOAD", ""))
except Exception:
    print(""); raise SystemExit
ti = d.get("tool_input") or {}
print(ti.get("file_path") or ti.get("path") or "")
PYEOF
)

case "$path" in
  */Epistemic-Humility-Research/CLAUDE.md|*/Epistemic-Humility-Research/.claude/CLAUDE.md)
    echo "BLOCKED: CLAUDE.md is a GENERATED MIRROR of AGENTS.md (regenerated by bin/sync_skills.py). A direct edit here is clobbered on the next sync. Edit the CANONICAL source instead, then propagate:
  1. edit AGENTS.md (repo root)
  2. python3 bin/sync_skills.py --write   # regenerates CLAUDE.md + the .claude/.agents/.codex skill mirrors
  3. python3 bin/sync_skills.py --check   # confirm in sync" >&2
    exit 2 ;;
  */Epistemic-Humility-Research/.claude/skills/*|*/Epistemic-Humility-Research/.agents/skills/*|*/Epistemic-Humility-Research/.codex/skills/*)
    echo "BLOCKED: this is a GENERATED skill MIRROR. Edit the canonical file under .skills/ (same relative path), then run 'python3 bin/sync_skills.py --write' and '--check'. Never hand-edit a mirror." >&2
    exit 2 ;;
esac
exit 0
