#!/usr/bin/env python3
"""Regenerate the task-backlog table inside TODO.md.

Scans ``backlog/tasks`` and ``backlog/drafts`` for non-done tasks, renders a
table (id, title, tier, status, priority, blocker/deps, experiment binding)
sorted by priority then created_date, plus a one-line count of tasks archived
in ``backlog/completed``, and splices it into the fenced
``<!-- BEGIN GENERATED: task-backlog -->`` / ``<!-- END GENERATED: task-backlog -->``
block in TODO.md. Everything outside the fence -- the "Prioritized backlog"
preamble, the gotcha paragraphs, the "Parked" section, the archive note -- is
preserved verbatim, so the file is safe to regenerate. Mirrors the pattern in
``bin/build_backlog_index.py`` (the amendment-status index).

Deterministic and idempotent.

Usage:
    python3 build_todo_index.py --write   # rewrite TODO.md in place
    python3 build_todo_index.py --check    # exit 1 if TODO.md is stale
    python3 build_todo_index.py            # print the block to stdout
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

SCRIPTS_DIR = Path(__file__).resolve().parent
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

import task as task_mod  # noqa: E402

BEGIN_MARKER = "<!-- BEGIN GENERATED: task-backlog -->"
END_MARKER = "<!-- END GENERATED: task-backlog -->"


def _sort_key(t: dict) -> tuple:
    priority_rank = task_mod.PRIORITY_ORDER.get(t.get("priority"), 99)
    return (priority_rank, t.get("created_date") or "", t.get("id") or "")


def _blocker_cell(t: dict, by_id: dict[str, dict]) -> str:
    parts = []
    unmet = task_mod._unmet_deps(t, by_id)  # noqa: SLF001 - intentional reuse
    if unmet:
        parts.append("blocked by " + ", ".join(unmet))
    blocker = (t.get("blocker") or "").strip()
    if blocker:
        parts.append(blocker)
    return "; ".join(parts) if parts else "-"


def render_block(root: Path) -> str:
    tasks = task_mod.iter_tasks(root)
    by_id = {t["id"]: t for t in tasks}
    open_tasks = sorted(
        (t for t in tasks if t.get("status") != "done"), key=_sort_key
    )
    done_count = sum(1 for t in tasks if t.get("status") == "done")

    lines = [
        BEGIN_MARKER,
        "",
        "_Generated by `bin/task` (`.skills/task-backlog`) from `backlog/tasks/` "
        "and `backlog/drafts/`. Do not edit inside this block by hand -- run "
        "`python3 .agents/skills/task-backlog/scripts/build_todo_index.py "
        "--write` (or `bin/task validate` first if it is stale) instead._",
        "",
        "| ID | Title | Tier | Status | Priority | Blocker / deps | Experiment |",
        "|----|-------|------|--------|----------|-----------------|------------|",
    ]
    for t in open_tasks:
        experiment = t.get("experiment") or "-"
        lines.append(
            f"| {t.get('id', '')} | {t.get('title', '')} | {t.get('tier', '')} "
            f"| {t.get('status', '')} | {t.get('priority', '')} "
            f"| {_blocker_cell(t, by_id)} | {experiment} |"
        )
    lines += [
        "",
        f"Done: {done_count} task(s) archived in `backlog/completed/`.",
        "",
        END_MARKER,
    ]
    return "\n".join(lines)


def splice(existing: str, block: str) -> str:
    if BEGIN_MARKER in existing and END_MARKER in existing:
        pre = existing.split(BEGIN_MARKER)[0]
        post = existing.split(END_MARKER, 1)[1]
        return f"{pre}{block}{post}"
    return f"{existing.rstrip()}\n\n{block}\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", default=None, help="repo root (default: discovered from cwd)")
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--write", action="store_true", help="rewrite TODO.md in place")
    g.add_argument("--check", action="store_true", help="exit 1 if TODO.md's generated block is stale")
    args = ap.parse_args(argv)

    root = Path(args.root).resolve() if args.root else task_mod.find_repo_root()
    todo_path = root / "TODO.md"
    block = render_block(root)

    if not args.write and not args.check:
        print(block)
        return 0

    existing = todo_path.read_text(encoding="utf-8") if todo_path.exists() else ""
    updated = splice(existing, block)

    if args.check:
        if updated != existing:
            sys.stderr.write(
                "TODO.md task-backlog block is stale. Run "
                "`python3 .agents/skills/task-backlog/scripts/build_todo_index.py --write`.\n"
            )
            return 1
        print("TODO.md task-backlog block is up to date.")
        return 0

    if updated != existing:
        todo_path.write_text(updated, encoding="utf-8")
        print(f"Wrote {todo_path.relative_to(root)} ({len(task_mod.iter_tasks(root))} tasks).")
    else:
        print("TODO.md already up to date; no change.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
